package com.ID1212.ID1212_Project_Intelij.Models;

import java.time.LocalDateTime;

public class QueuePost {
    private Long id;
    private String location;
    private String comment;
    private Boolean help;
    private Boolean present;
    private LocalDateTime localDateTime;

    protected QueuePost() {
    }

    /**
     * Queue post by students
     * @param id from db
     * @param location submitted by student
     * @param comment submitted by student
     * @param help checkbox ticked by student
     * @param present checkbox ticked by student
     * localDateTime time and date queue post passed by student
     */
    public QueuePost(Long id,
                     String location,
                     String comment,
                     Boolean help,
                     Boolean present
                     ) {
        this.id = id;
        this.location = location;
        this.comment = comment;
        this.help = help;
        this.present = present;
        this.localDateTime = LocalDateTime.now();
    }

    /**
     * Without id because generated by postgres db
     * @param location submitted by student
     * @param comment submitted by student
     * @param help checkbox ticked by student
     * @param present checkbox ticked by student
     * localDateTime time and date queue post passed by student
     */
    public QueuePost(String location,
                     String comment,
                     Boolean help,
                     Boolean present) {
        this.location = location;
        this.comment = comment;
        this.help = help;
        this.present = present;
        this.localDateTime = LocalDateTime.now();
    }

    public Long getId() {
        return id;
    }

    public String getLocation() {
        return location;
    }

    public String getComment() {
        return comment;
    }

    public Boolean getHelp() {
        return help;
    }

    public Boolean getPresent() {
        return present;
    }

    public LocalDateTime getLocalDateTime() {
        return localDateTime;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public void setHelp(Boolean help) {
        this.help = help;
    }

    public void setPresent(Boolean present) {
        this.present = present;
    }

    public void setLocalDateTime(LocalDateTime localDateTime) {
        this.localDateTime = localDateTime;
    }

    @Override
    public String toString() {
        return "QueuePost{" +
                "id=" + id +
                ", location='" + location + '\'' +
                ", comment='" + comment + '\'' +
                ", help=" + help +
                ", present=" + present +
                ", localDateTime=" + localDateTime +
                '}';
    }
}
